openapi: 3.0.0
info:
  title: Denver BIPOC Businesses
  version: '1.0'
  description: ''
  contact:
    name: Ari Gibson
    email: arimgibson@gmail.com
    url: 'https://github.com/aristhings/denver-bipoc'
  license:
    name: GNU GPL
    url: 'https://github.com/aristhings/denver-bipoc/blob/master/LICENSE'
servers:
  - url: 'https://denver-bipoc.herokuapp.com/api/'
paths:
  /businesses:
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-businesses
      description: Returns a categorized list of all businesses in the database.
      parameters: []
components:
  schemas: {}
  securitySchemes: {}
